export type ResourceType = "article" | "lesson";

export type ResourceItem = {
  slug: string;
  title: string;
  type: ResourceType;
  description: string;
  excerpt: string;
  readTime: string;
  image: string;
  videoPlanned?: boolean;
  seoIntent: string;
  content?: string;
  order?: number;
  category?: string;
  isLocked?: boolean; 
};

export const RESOURCES: ResourceItem[] = [
  {
    slug: "what-to-do-next",
    title: "What to Do Next + FramerKit Workflow Recap",
    type: "lesson",
    order: 24,
    isLocked: true,
    category: "Final Path",
    description: "Understand what to do after learning the basics and how to continue improving your workflow.",
    excerpt: "Review the full workflow and learn how to move forward with real projects.",
    readTime: "6 min",
    image: "https://via.placeholder.com/1280x720?text=Next+Steps",
    videoPlanned: true,
    seoIntent: "framer workflow recap, what to do after learning web design, next steps framer",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "zero-to-first-client",
    title: "From Zero to First Client (Full Path)",
    type: "lesson",
    order: 23,
    isLocked: true,
    category: "Final Path",
    description: "Understand the full path from learning Framer to getting your first client.",
    excerpt: "See how everything connects into one clear workflow from zero to freelance work.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Full+Path",
    videoPlanned: true,
    seoIntent: "learn framer full path, from beginner to freelance web design, first client guide",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-one-page-website",
    title: "Build a Simple One Page Website",
    type: "lesson",
    order: 15,
    isLocked: true,
    category: "Build Websites",
    description: "Learn how to build a simple and effective one-page website using FramerKit.",
    excerpt: "Create a clean one-page website with a clear structure and flow.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=One+Page+Website",
    videoPlanned: true,
    seoIntent: "one page website framer, simple landing page design, single page layout",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-app-landing-page",
    title: "Build an App Landing Page",
    type: "lesson",
    order: 14,
    isLocked: true,
    category: "Build Websites",
    description: "Learn how to build a modern app landing page using FramerKit.",
    excerpt: "Create a clean app landing page that highlights features and drives downloads.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=App+Landing",
    videoPlanned: true,
    seoIntent: "app landing page framer, mobile app website design, app landing layout",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-faster-with-templates",
    title: "Build Faster with Templates (Pro Workflow)",
    type: "lesson",
    order: 22,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn how to use templates to build websites even faster using a professional workflow.",
    excerpt: "Understand how to combine templates and sections for maximum speed.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Pro+Workflow",
    videoPlanned: true,
    seoIntent: "framer templates workflow, build faster framer templates, framerkit templates usage",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "deliver-projects-without-revisions",
    title: "How to Deliver Projects (Without Endless Revisions)",
    type: "lesson",
    order: 21,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn how to deliver projects smoothly and avoid endless revisions.",
    excerpt: "Understand how to structure your process to keep projects under control.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Project+Delivery",
    videoPlanned: true,
    seoIntent: "freelance project delivery, avoid revisions web design, client revisions problem",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "how-to-talk-to-clients",
    title: "How to Talk to Clients (Without Stress)",
    type: "lesson",
    order: 20,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn how to communicate with clients clearly and confidently.",
    excerpt: "Understand how to talk to clients, ask the right questions, and avoid confusion.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Client+Communication",
    videoPlanned: true,
    seoIntent: "freelance client communication, talk to clients web design, client questions web design",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "how-to-price-work",
    title: "How to Price Your Work",
    type: "lesson",
    order: 19,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn how to price your web design work correctly as a beginner.",
    excerpt: "Understand how to set prices, avoid underpricing, and grow your income.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Pricing",
    videoPlanned: true,
    seoIntent: "how to price web design, freelance pricing beginner, web design rates",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "find-first-clients",
    title: "How to Find Your First Clients",
    type: "lesson",
    order: 18,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn simple ways to find your first freelance clients using your skills.",
    excerpt: "Understand where to look for clients and how to get your first projects.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Find+Clients",
    videoPlanned: true,
    seoIntent: "find freelance clients web design, first client web designer, freelance beginners guide",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "framerkit-for-freelance",
    title: "How to Use FramerKit for Freelance Work",
    type: "lesson",
    order: 17,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn how to use FramerKit to complete freelance projects faster and more efficiently.",
    excerpt: "Understand how to build client websites quickly and deliver better results.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Freelance+Work",
    videoPlanned: true,
    seoIntent: "framer freelance work, build client websites fast, framerkit freelance workflow",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "speed-tricks-framer",
    title: "Speed Tricks: Work 2x Faster in Framer",
    type: "lesson",
    order: 16,
    isLocked: true,
    category: "Freelance & Money",
    description: "Learn simple tricks that help you build pages much faster in Framer.",
    excerpt: "Speed up your workflow by removing unnecessary steps and using smart habits.",
    readTime: "6 min",
    image: "https://via.placeholder.com/1280x720?text=Speed+Tricks",
    videoPlanned: true,
    seoIntent: "framer speed tips, design faster framer, workflow optimization framer",
    // Note: This lesson has a dedicated React component page
  },

  {
    slug: "build-agency-website",
    title: "Build an Agency Website",
    type: "lesson",
    order: 13,
    isLocked: true,
    category: "Build Websites",
    description: "Learn how to build a professional agency website using FramerKit.",
    excerpt: "Create an agency website that looks clean, structured, and trustworthy.",
    readTime: "9 min",
    image: "https://via.placeholder.com/1280x720?text=Agency+Website",
    videoPlanned: true,
    seoIntent: "agency website framer, build agency site, web design agency layout",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-portfolio-website",
    title: "Build a Portfolio Website",
    type: "lesson",
    order: 12,
    isLocked: true,
    category: "Build Websites",
    description: "Learn how to build a clean and modern portfolio website using FramerKit.",
    excerpt: "Create a portfolio that showcases your work and builds trust.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Portfolio+Website",
    videoPlanned: true,
    seoIntent: "portfolio website framer, build portfolio website, designer portfolio layout",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-saas-landing-page",
    title: "Build a SaaS Landing Page",
    type: "lesson",
    order: 11,
    isLocked: true,
    category: "Build Websites",
    description: "Learn how to build a modern SaaS landing page using FramerKit.",
    excerpt: "Create a clean SaaS landing page with proper structure and flow.",
    readTime: "9 min",
    image: "https://via.placeholder.com/1280x720?text=SaaS+Landing",
    videoPlanned: true,
    seoIntent: "saas landing page framer, build saas website, framerkit saas layout",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "common-mistakes-framer",
    title: "Common Mistakes Beginners Make in Framer",
    type: "lesson",
    order: 10,
    isLocked: true,
    category: "Core Skills",
    description: "Avoid the most common mistakes when building pages in Framer.",
    excerpt: "Learn what beginners do wrong and how to fix it quickly.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Common+Mistakes",
    videoPlanned: true,
    seoIntent: "framer mistakes beginners, web design mistakes, landing page errors",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "speed-workflow-build-fast",
    title: "Speed Workflow: Build Pages in Minutes",
    type: "lesson",
    order: 9,
    isLocked: true,
    category: "Core Skills",
    description: "Learn how to build pages extremely fast using FramerKit workflow.",
    excerpt: "Understand how to reduce build time and create pages in minutes instead of hours.",
    readTime: "6 min",
    image: "https://via.placeholder.com/1280x720?text=Speed+Workflow",
    videoPlanned: true,
    seoIntent: "build website fast framer, framerkit workflow speed, fast landing page design",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "wireframe-design-dark-modes",
    title: "Wireframe, Design, Dark: Choose the Right Version",
    type: "lesson",
    order: 8,
    isLocked: true,
    category: "Core Skills",
    description: "Learn how to choose between wireframe, design, and dark versions in FramerKit.",
    excerpt: "Understand when to use each version to work faster and build better pages.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Wireframe+Design+Dark",
    videoPlanned: true,
    seoIntent: "framer wireframe vs design, dark ui framerkit, section versions framer",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "improve-page-small-changes",
    title: "Improve Your Page: Small Changes That Make a Big Difference",
    type: "lesson",
    order: 7,
    isLocked: true,
    category: "Core Skills",
    description: "Learn how small improvements can make your page look more professional and polished.",
    excerpt: "Understand what details separate basic layouts from high-quality designs.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Improve+Your+Page",
    videoPlanned: true,
    seoIntent: "improve web design, ui polish tips, better landing page design",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "content-and-copy-sections",
    title: "Content & Copy: What to Write in Your Sections",
    type: "lesson",
    order: 6,
    isLocked: true,
    category: "Core Skills",
    description: "Learn what to write in each section so your page feels clear and professional.",
    excerpt: "Understand how to write simple and effective content for your layouts.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Content+and+Copy",
    videoPlanned: true,
    seoIntent: "landing page copywriting, what to write landing page, website content structure",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "navbar-to-cta-flow",
    title: "Navbar to CTA: Guide Users Through Your Page",
    type: "lesson",
    order: 5,
    isLocked: true,
    category: "Getting Started",
    description: "Learn how to structure your page so users clearly understand what to do and where to click.",
    excerpt: "Understand how to guide users from the first screen to the final action.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Navbar+to+CTA",
    videoPlanned: true,
    seoIntent: "landing page structure ux, navbar to cta flow, conversion design framer",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "responsive-layout-framer",
    title: "Responsive Layout in Framer: Make Your Design Work Everywhere",
    type: "lesson",
    order: 4,
    isLocked: true,
    category: "Getting Started",
    description: "Learn how to make your layouts responsive and look good on all screen sizes.",
    excerpt: "Understand how to adapt your design for desktop, tablet, and mobile in Framer.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Responsive+Layout",
    videoPlanned: true,
    seoIntent: "framer responsive design, framer mobile layout, adaptive design framer",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "combine-sections-better-layouts",
    title: "Combine Sections: Build Better Layouts",
    type: "lesson",
    order: 3,
    isLocked: true,
    category: "Getting Started",
    description: "Learn how to combine sections правильно to create clean and balanced layouts.",
    excerpt: "Understand how to structure sections so your pages look professional and consistent.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=Combine+Sections",
    videoPlanned: true,
    seoIntent: "framer layout design, combine sections framer, website structure design",
    // Note: This lesson has a dedicated React component page
  },

  {
    slug: "framerkit-workflow-pages",
    title: "FramerKit Workflow: Build Pages the Right Way",
    type: "lesson",
    order: 2,
    isLocked: true,
    category: "Getting Started",
    description: "Learn the correct workflow for building pages in Framer using FramerKit.",
    excerpt: "Understand how to build pages faster using a structured workflow instead of random design.",
    readTime: "7 min",
    image: "https://via.placeholder.com/1280x720?text=FramerKit+Workflow",
    videoPlanned: true,
    seoIntent: "framer workflow tutorial, build pages framer, framerkit workflow",
    // Note: This lesson has a dedicated React component page
  },
  {
    slug: "build-first-landing-fast",
    title: "Build Your First Landing Fast",
    type: "lesson",
    order: 1,
    isLocked: false,
    category: "Getting Started",
    description: "Build a complete landing page in Framer using FramerKit sections in minutes.",
    excerpt: "Learn how to quickly assemble a landing page using sections and basic structure.",
    readTime: "8 min",
    image: "https://via.placeholder.com/1280x720?text=Build+Landing+Fast",
    videoPlanned: true,
    seoIntent: "framer landing page tutorial, build landing fast framer, framerkit sections",
    // Note: This lesson has a dedicated React component page at /pages/Lessons/BuildFirstLandingFast.tsx
  },
  {
    slug: "templates-vs-sections-framerkit",
    title: "Templates vs Sections in FramerKit",
    type: "article",
    category: "Workflow",
    description: "Understand when to use templates and when to use sections in FramerKit.",
    excerpt: "Learn the difference between templates and sections and how to use both effectively.",
    readTime: "6 min",
    image: "https://via.placeholder.com/1280x720?text=Templates+vs+Sections",
    seoIntent: "framer templates vs sections, framerkit templates, website structure framer",
    // Note: This lesson has a dedicated React component page
  },
  {
  slug: "color-palette-in-framerkit",
  title: "Color Palette in FramerKit",
  category: "Design System",
  type: "article",
  description: "Use structured color palettes in FramerKit to build flexible and scalable design systems.",
  excerpt: "Learn how to use color palettes in FramerKit for full control over your design system.",
  readTime: "6 min",
  image: "https://via.placeholder.com/1280x720?text=Color+Palette+in+FramerKit",
  seoIntent: "framer color palette, design system colors framer, ui color system",
  // Note: This lesson has a dedicated React component page
  },
  {
    slug: "color-sets-in-framerkit",
    title: "Color Sets in FramerKit",
    category: "Design System",
    type: "article",
    description:
      "Use ready-made color sets in FramerKit to keep your design consistent and apply a full color system in seconds.",
    excerpt:
      "Learn how to use Color Sets in FramerKit, why they matter, and how to add them through the plugin inside Framer.",
    readTime: "5 min",
    image: "https://via.placeholder.com/1280x720?text=Color+Sets+in+FramerKit",
    seoIntent:
      "framer color system, framerkit color sets, framer plugin colors, ui color palette",
    // Note: This lesson has a dedicated React component page
  },
];

export const RESOURCE_BY_SLUG: Record<string, ResourceItem> = Object.fromEntries(
  RESOURCES.map((item) => [item.slug, item])
);
